<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#004f2e"><title>Course Voices · A shared space for learning</title><link rel="stylesheet" href="assets/style.css?v=20260912-licenses"><script src="assets/app.js?v=20260912-licenses" defer></script></head>
<body><a class="skip" href="#posts">Skip to posts</a>
<div class="shell"><header class="topbar"><a class="brand" href="./"><span class="brand-icon" aria-hidden="true">v.</span> course voices</a><div class="top-actions"><a href="admin.php" class="text-link">Instructor space <span aria-hidden="true">↗</span></a></div></header>
<main><section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="dot"></span><span id="course-label">A COMMUNITY OF LEARNERS</span></div><h1 id="site-title">Many voices.<br><em>Shared learning.</em></h1><p id="description">Ideas, reflections, and discoveries from across the class, brought together in one place.</p></div></section>
<section class="feed-heading"><div><p class="eyebrow">THE COLLECTIVE NOTEBOOK</p><h2>From our blogs<span class="count" id="post-count">—</span></h2></div><label class="semester-label"><span class="sr-only">Course and semester</span><select id="semester" aria-label="Course and semester"></select></label></section>
<div class="workspace"><div class="feed-main"><div class="toolbar"><div class="tabs" role="group" aria-label="Reading status"><button class="active" data-filter="all" aria-pressed="true">All posts</button><button data-filter="unread" aria-pressed="false">Unread <span id="unread-count"></span></button><button data-filter="read" aria-pressed="false">Read</button></div><label class="search"><span aria-hidden="true">⌕</span><span class="sr-only">Search posts</span><input id="search" type="search" placeholder="Search posts…" aria-label="Search posts"></label></div>
<div class="results-line"><span id="results">Loading the conversation…</span><select id="sort" aria-label="Sort posts"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></div>
<p id="notice" class="notice" hidden role="status"></p><div id="posts" class="post-grid" aria-live="polite"><div class="loading">Gathering the latest voices…</div></div><button id="load-more" class="load-more" hidden>More from the class <span aria-hidden="true">↓</span></button></div>
<aside class="sidebar"><div class="side-title"><h2>Our contributors</h2><span id="people-count"></span></div><button class="everyone selected" id="everyone">Everyone <span aria-hidden="true">↗</span></button><div id="contributors" class="people"></div><div class="reading-note"><span aria-hidden="true">◷</span><h3>A little reading companion</h3><p>Open a post to mark it read. Your place is remembered in this browser, without an account.</p><p class="small">Read status stays on this device and may reset if browser data is cleared.</p></div><p class="updated" id="updated"></p></aside></div>
</main><footer><div class="footer-credit"><p>© 2026 Dr. Alec Couros · Course Voices</p><p>Original site content: <a rel="license" href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a> · Code: <a href="https://github.com/courosa/course-voices/blob/main/LICENSE">MIT License</a> · <a href="https://github.com/courosa/course-voices">View on GitHub</a></p><p class="rights-note">Student posts remain the work of their respective authors and retain their original licenses.</p></div><a href="admin.php">Instructor space <span aria-hidden="true">↗</span></a></footer></div></body></html>
